config/routes.rb
Rails.application.routes.draw do
  
  root "organisations#index"

  use_doorkeeper
  devise_for :users, :controllers => { registrations: 'registrations' }
  devise_scope :user do
    get "login", to: "devise/sessions#new"
    get "register", to: "devise/registrations#new"
  end
  
  # community users
  resources :organisations, only: [:index, :new, :create, :edit, :update]
  resources :services, except: [:index] do
    post "confirmation", to: "services#confirmation"
    resources :feedback, only: [:index, :create]
  end
  
  # https://trello.com/c/aFtIf3QZ/242-prevent-community-users-from-managing-users-in-their-organisation
  # resources :members, only: [:new, :create, :destroy]

  # admin users
  namespace :admin do
    root "dashboard#index"
    resources :services, except: :edit do
      resources :watch, only: [:create, :destroy]
      resources :notes, only: [:create, :destroy]
      resources :versions, only: [:index]
      collection do 
        resources :archive, only: [:update]
        resources :requests, only: [:index, :update]
      end
    end
    resources :organisations, except: :edit do
      get "timetable", to: "organisations#timetable"
    end
    resources :labels, only: [:index, :destroy]
    resources :locations, except: [:edit, :new, :create]
    resources :taxonomies, except: [:new, :edit]
    resources :feedbacks, only: [:index]
    resources :ofsted, only: [:index, :show] do
      put "dismiss"
      get "versions"
      collection do
        get "pending"
      end
    end
    resources :activity, only: [:index, :show]
    resources :custom_field_sections, except: [:edit]
    resources :users, except: [:edit] do
      post :reset, on: :member
      put :reactivate, on: :member
    end
    resource :settings, only: [:edit, :update]
    resources :send_needs, except: [:edit, :show, :destroy, :update] do
      collection do
        post 'create_defaults', to: "send_needs#create_defaults"
      end
    end
    resources :accessibilities, except: [:edit, :show, :destroy, :update] do
      collection do
        post 'create_defaults', to: "accessibilities#create_defaults"
      end
    end
    resources :suitabilities, except: [:edit, :show, :destroy, :update] do
      collection do
        post 'create_defaults', to: "suitabilities#create_defaults"
      end
    end
  end

  # api
  namespace :api do
    namespace :v1 do
      resources :taxonomies, only: [:index]
      resources :send_needs, only: [:index]
      resources :suitabilities, only: [:index]
      resources :accessibilities, only: [:index]
      get "me", to: "me#show"
      resources :services, only: [:index, :show]
    end
  end

end

app/controllers/admin/services_controller.rb
class Admin::ServicesController < Admin::BaseController
  before_action :set_service, only: [:update, :destroy]
  before_action :load_custom_field_sections, only: [:show, :update, :destroy, :new, :create]
  skip_before_action :set_counts, only: :show

  def index
    @filterrific = initialize_filterrific(
      Service,
      params[:filterrific],
      select_options: {
        sorted_by: Service.options_for_sorted_by,
        in_taxonomy: Taxonomy.options_for_select,
        with_status: Service.options_for_status,
        tagged_with: Service.options_for_labels
      },
      persistence_id: false,
      default_filter_params: {},
      available_filters: [
        :in_taxonomy, 
        :tagged_with, 
        :with_status, 
        :search, 
        :sorted_by
      ],
    ) or return

    @services = @filterrific.find.page(params[:page]).includes(:organisation, :service_taxonomies, :taxonomies)
    @services = @services.in_directory(params[:directory]) if params[:directory].present?

    # shortcut nav
    @services = @services.ofsted_registered if params[:ofsted] === "true"
    if params[:archived] === "true"
      @services = @services.discarded
    else
      @services = @services.kept
    end

  end

  def show
    @service = Service.includes(:organisation, :contacts, :cost_options, :feedbacks, :links,
                                :local_offer, :locations, :regular_schedules,
                                notes: [user: :watches], versions: [user: :watches]).find(params[:id])

    @watched = current_user.watches.where(service_id: @service.id).exists?
    @organisations = Organisation.all
    @suitabilities = Suitability.all
    @send_needs = SendNeed.all
    @accessibilities = Accessibility.all
    @directories = Directory.all

    if @service.versions.length > 4
      @versions = @service.versions.first(3)
      @versions.push(@service.versions.last)
    else
      @versions = @service.versions
    end
  end

  def update
    # force paper trail version to be saved
    @service.updated_at = Time.now
    if @service.update(service_params)
      redirect_to admin_service_url(@service), notice: "Service has been updated."
    else
      render "show"
    end
  end

  def new
    @service = Service.new
    @organisations = Organisation.all
    @accessibilities = Accessibility.all
    @send_needs = SendNeed.all
    @suitabilities = Suitability.all
    @ofsted_item = OfstedItem.find(params[:ofsted_item_id]) if params[:ofsted_item_id]
  end

  def create
    @service = Service.new(service_params)
    if @service.save
      redirect_to admin_service_url(@service), notice: "Service has been created."
    else
      render "new"
    end
  end

  def destroy
    @service.archive
    redirect_to admin_services_path, notice: "That service has been archived."
  end

  private

  def set_service
    @service = Service.find(params[:id])
  end

  def load_custom_field_sections
    @custom_field_sections = CustomFieldSection.includes(:custom_fields).visible_to(current_user)
  end

  def service_params
    result_params = params.require(:service).permit(
      :name,
      :organisation_id,
      :description,
      :url,
      :referral_url,
      :facebook_url, 
      :twitter_url, 
      :youtube_url, 
      :instagram_url, 
      :linkedin_url,
      :visible,
      :visible_from,
      :visible_to,
      :min_age,
      :max_age,
      :temporarily_closed,

      :age_band_under_2,
      :age_band_2,
      :age_band_3_4,
      :age_band_5_7,
      :age_band_8_plus,
      :age_band_all,

      :label_list,
      :needs_referral,
      :marked_for_deletion,
      :free,
      :ofsted_item_id,
      directory_ids: [],
      taxonomy_ids: [],
      send_need_ids: [],
      suitability_ids: [],
      local_offer_attributes: [
        :id,
        :description,
        :link,
        :_destroy,
        survey_answers: [
          :question,
          :answer
        ]
      ],
      cost_options_attributes: [
        :id,
        :option,
        :amount,
        :cost_type,
        :_destroy,
      ],
      regular_schedules_attributes: [
        :id,
        :opens_at,
        :closes_at,
        :weekday,
        :_destroy,
      ],
      contacts_attributes: [
        :id,
        :name,
        :title,
        :visible,
        :email,
        :phone,
        :_destroy,
      ],
      links_attributes: [
        :id,
        :label,
        :url,
        :_destroy
      ],
      locations_attributes: [
        :id,
        :name,
        :address_1,
        :city,
        :postal_code,        
        :visible,
        :mask_exact_address,
        :preferred_for_post,
        :_destroy,
        accessibility_ids: []
      ],
      meta_attributes: [
        :id,
        :key,
        :value
      ]
    )

    # map fields_for submitted values, which are of the form 'id => { answer: text }' into an array of '[{ id: id, answer: text }]'
    if result_params['local_offer_attributes']&.[]('survey_answers')
      result_params['local_offer_attributes']['survey_answers'] =
        result_params['local_offer_attributes']['survey_answers'].to_h.map{|k,v| { id: k.to_i, answer: v['answer']}}
    end

    result_params
  end

end

app/controllers/api/v1/services_controller.rb
class API::V1::ServicesController < ApplicationController
    skip_before_action :authenticate_user!
    before_action -> { doorkeeper_authorize! :admin }

    # /api/v1/services?format=full|mini?ids=1,2,3
    def index
        format = params[:format]
        ids = params[:ids]
        errors = 0

        # no format no data
        errors += 1 unless ['full', 'mini'].include?(format) 

        # if ids are present then we only want to return those services
        # we only allow max 20 services to be requested at a time
        if ids.present?
            ids = ids.split(',').map(&:to_i)
            errors += 1 if ids.count > 20
        end


        if errors > 0
            render json: { error: 'Bad request' }, status: :bad_request
        else
            services = Service.order("updated_at DESC")
            services = services.where(id: ids) if ids
            services = services.page(params[:page]).per(20)
            if format == 'full'
                # @TODO this will return be a paginated list of services but it needs tests to ensure its open referral compliance 
                # render json: json_tree(services, services.map { |s| IndexedServicesSerializer.new(s).as_json })
            elsif format == 'mini'
                render json: json_tree(services, services.map { |s| mini_services_json_tree(s) })
            end
        end

    end

    # /api/v1/services/:id
    def show
        format = params[:format]
        if ['full', 'mini'].include?(format)
            service = Service.find(params[:id])
            if format == 'full'
                # @TODO this will return be a paginated list of services but it needs tests to ensure its open referral compliance 
                # render json: IndexedServicesSerializer.new(service).as_json
            elsif format == 'mini'
                render json: mini_services_json_tree(service)
            end
        else
            render json: { error: 'Bad request' }, status: :bad_request
        end
    end

    private

    def json_tree(services, service_content)
        {
            number: services.page(params[:page]).current_page,
            size: services.page(params[:page]).limit_value,
            totalPages: services.page(params[:page]).total_pages,
            totalElements: services.total_count,
            first: services.page(params[:page]).first_page?,
            last: services.page(params[:page]).last_page?,
            content: service_content
        }
    end

    def mini_services_json_tree(s)
        {
            id: s.id,
            name: s.name,
            status: s.status
        }
    end

end

app/controllers/services_controller.rb
# This controller lets community users manage their services.
class ServicesController < ApplicationController
    before_action :no_admins
    before_action :set_service, except: [:new, :create]

    def new
        @service = current_user.organisation.services.new
    end

    def create
        @service = current_user.organisation.services.new(service_params)
        @service.approved = false
        if @service.save
            session[:currently_creating] = @service.id
            # mark first item done
            session[:completed_sections] = ["name_and_description"]
            redirect_to service_path(@service)
        else
            render :new
        end
    end

    def show
        @currently_creating = session[:currently_creating] === @service.id
        @completion_count = session[:completed_sections].try(:length) || 0
    end

    def edit
        @accessibilities = Accessibility.all if params[:section] == 'locations'
        @send_needs = SendNeed.all if params[:section] == 'special_educational_needs_and_disabilities'
        @suitabilities = Suitability.all if params[:section] == 'suitable_for'
        render "_edit_#{params[:section]}"
    end

    def confirmation
        session[:currently_creating] = nil
        session[:completed_sections] = []
    end

    def update
        if params[:section] && session[:completed_sections]
            session[:completed_sections] |= [params[:section]]
        end
        if params[:service]
            @service.approved = false
            # force paper trail version to be saved
            @service.updated_at = Time.now
            if @service.update(service_params)
                redirect_to service_path(@service)
            else
                render "_edit_#{params[:section]}"
            end
        else
            redirect_to service_path(@service)
        end
    end

    def destroy
        @service.approved = false
        @service.archive
        redirect_to organisations_path, notice: "That service will be removed as soon as we approve it."
    end

    private

    def set_service
        @service = current_user.organisation.services.find(params[:id] || params[:service_id])
        @custom_field_sections = CustomFieldSection.includes(:custom_fields).visible_to(current_user)
    end

    def service_params
        result_params = params.require(:service).permit(
            :name,
            :description,
            :url,
            :email,
            :visible_from,
            :visible_to,
            :visible,
            :bccn_member,
            :current_vacancies,
            :pick_up_drop_off_service,
            :free,
            :needs_referral, 
            :referral_url,
            :min_age,
            :max_age,
            :temporarily_closed,

            :age_band_under_2,
            :age_band_2,
            :age_band_3_4,
            :age_band_5_7,
            :age_band_8_plus,
            :age_band_all,
            #taxonomy_ids: []
            send_need_ids: [],
            suitability_ids: [],
            local_offer_attributes: [
                :id,
                :description,
                :link,
                :_destroy,
                survey_answers: [
                    :question,
                    :answer
                ]
            ],
            cost_options_attributes: [
                :id,
                :option,
                :amount,
                :cost_type,
                :_destroy,
            ],
            regular_schedules_attributes: [
                :id,
                :opens_at,
                :closes_at,
                :weekday,
                :_destroy,
            ],
            contacts_attributes: [
                :id,
                :name,
                :title,
                :visible,
                :email,
                :phone,
                :_destroy,
            ],
            links_attributes: [
                :id,
                :label,
                :url,
                :_destroy
            ],
            locations_attributes: [
                :id,
                :name,
                :address_1,
                :city,
                :postal_code,
                :visible,
                :mask_exact_address,
                :preferred_for_post,
                :_destroy,
                accessibility_ids: []
            ],
            meta_attributes: [
                :id,
                :key,
                :value
            ]
        )
        # map fields_for submitted values, which are of the form 'id => { answer: text }' into an array of '[{ id: id, answer: text }]'
        if result_params['local_offer_attributes']&.[]('survey_answers')
            result_params['local_offer_attributes']['survey_answers'] =
                result_params['local_offer_attributes']['survey_answers'].to_h.map{|k,v| { id: k.to_i, answer: v['answer']}}
        end
        result_params
    end

end

app/helpers/services_helper.rb
module ServicesHelper

  def mark_unapproved_field(attribute)
    if @service.unapproved_changes?(attribute) && current_user.admin?
      "field--changed"
    end
  end

  def mark_unapproved_local_offer
    if @service.unapproved_changes?("local_offer") && current_user.admin?
      content_tag(:div, class: "changed") do
        yield
      end
    else
      content_tag(:div) do
        yield
      end
    end
  end

  def mark_unapproved_array(attribute)
    if @service.unapproved_changes?(attribute) && current_user.admin?
      content_tag(:div, class: "changed") do
        yield
      end
    else
      content_tag(:div) do
        yield
      end
    end
  end
end

app/views/admin/services/_list.html.erb
<table class="table test-services">
  <thead>
    <tr>
      <th class="visually-hidden">ID</th>
      <th>Name</th>
      <th>Organisation</th>
      <th>Taxonomies</th>
      <th>Last updated</th>
      <th>Status</th>
      <th class="visually-hidden">Notes</th>
    </tr>
  </thead>
  <tbody>
    <% @services.each do |s| %>
      <tr>
        <td><span class="table__small"><%= s.id %></span></td>
        <td>
          <strong><%= link_to s.display_name.truncate(30), admin_service_path(s), title: s.display_name %></strong>
        </td>
        <td>
          <%= render "shared/poppables/organisation", o: s.organisation if s.organisation %>
        <td>
          <% s.taxonomies.each do |t| %>
            <%= link_to t.name, admin_taxonomy_path(t), class: "taxonomy" if t.parent_id == nil %>
          <% end %>
        </td>
        <td><%= time_ago_in_words(s.updated_at).humanize %> ago</td>
        <td><%= status_tag(s.status) %></td>
        <td>
          <% if s.notes.size > 0 %>
            <span class="table-icon table-icon--notes">
              <%= s.notes.size %>
            </span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/services/_notes.html.erb
<%= render "shared/collapsible", name: "Notes", count: @service.notes.length, id: "service-notes", help_text: "Use notes to log phone calls and other information not captured automatically" do %>

  <div class="notes-list">
    <% if @service.notes.present? %>
      <% @service.notes.each do |n| %>
        <article class="notes-list__note">
          <header class="notes-list__note-header">
            <% if n.user.present? %>
              <strong><%= render "shared/poppables/user", u: n.user %></strong>
            <% elsif n.deleted_user_name %>
              <strong><%= render "shared/poppables/deleted_user", u: n.deleted_user_name %></strong>
            <% end %>

            | <%= time_ago_in_words(n.created_at).humanize %> ago 
            <% if n.user === current_user %>| <%= link_to "Remove", admin_service_note_path(@service, n), method: "delete", data: {confirm: "Are you sure you want to remove this note?"} %><% end %>
          </header>
          <p><%= n.body %></p>
        </article>
      <% end %>
    <% end %>
  </div>

  <%= form_for [:admin, @service, @service.notes.new], url: admin_service_notes_path(@service) do |f| %>
    <div class="field">
      <%= f.label :body, class: "visually-hidden" %>
      <%= f.text_area :body , class: "field__input", placeholder: "Type a note...", maxlength: 200, required: true %>
    </div>
    <%= f.button "Add note", class: "button button--small button--add"%>
  <% end %>

<% end %>

app/views/admin/services/_notices.html.erb
<% unless @service.approved? %>
    <div class="notice notice--pending">
        <div class="notice__body">

            <% if @service.discarded?  %>

                <p>Someone has requested that this service be archived. Do you want to archive it?</p>
                
                <%= link_to "Yes, archive", admin_request_path(@service), method: "patch", class: "notice__action", data: {confirm: "Are you sure? The service will be removed from all listings."} %>
                <span class="notice__divider">|</span>
                <%= link_to "No, restore", admin_archive_path(@service), method: "patch", class: "notice__action", data: {confirm: "Are you sure? The service will be visible to users again."} %>

            <% elsif @service.last_approved_snapshot %>

                <p>Someone has made changes to <strong><%= @service.unapproved_fields.map{|el| el.humanize}.join(", ") %></strong>. Do you want to approve them?</p>
                
                <%= link_to "Approve", admin_request_path(@service), method: "patch", class: "notice__action", data: {confirm: "Are you sure? Approving these changes makes them publicly visible."} %>
                <span class="notice__divider">|</span>
                <%= link_to "Compare versions", admin_service_versions_path(@service), class: "notice__action" %>

            <% else %>

                <p>This is a new service. Do you want to approve it?</p>
                <%= link_to "Approve", admin_request_path(@service), method: "patch", class: "notice__action", data: {confirm: "Are you sure? Approving these changes makes them publicly visible."} %>

            <% end %>

        </div>      
    </div>

<% else %>

    <% if @service.discarded? %>
        <div class="notice notice--cross">
            <div class="notice__body">
                <p>This service is archived and isn't visible</p>
                <%= link_to "Restore", admin_archive_path(@service), method: "patch", class: "notice__action", data: {confirm: "Are you sure? The service will be visible to users again."} %>
            </div>
        </div>
    <% end %>

<% end %>

app/views/admin/services/new.html.erb
<% content_for :header do %>

<% if @ofsted_item.present? %>
<div class="notice">
    <div class="notice__body">
        <p>
            You're creating a service linked to an Ofsted feed item:
            <%= link_to @ofsted_item.display_name, admin_ofsted_path(@ofsted_item) %>
        </p>
    </div>
</div>
<% end %>

<%= render "shared/dynamic-back-link", text: "Back to services", path: admin_services_path %>
<h1 class="page-header__title two-thirds">Add a new service</h1>
<% end %>


<div class="with-sidebar">

    <div>
        <%= form_for [:admin, @service], data: {warn_unsaved_changes: true}, builder: OutpostFormBuilder do |s| %>

        <%= s.hidden_field :ofsted_item_id, value: params[:ofsted_item_id] %>

        <%= render "shared/errors", model: @service %>

        <%= render "admin/services/editors/basics", s: s %>

        <% if Directory.any? %>
            <%= render "shared/collapsible", name: "Directories", count: @service.directories.length, id: "directories-editor", help_text: "Select which directories you want the service to appear in" do %>
                <%= render "admin/services/editors/directories", s: s %>
            <% end %>
        <% end %>

        <%= render "shared/collapsible", name: "Contacts", count: @service.contacts.length, id: "contacts-editor", help_text: "Provide individual points of contact for users." do %>
        <%= render "admin/services/editors/contacts", s: s %>
        <% end %>

        <%= render "shared/collapsible", name: "Taxonomies", count: @service.taxonomies.length, id: "taxonomy-editor", help_text: "Help users understand what kind of service this is." do %>
          <% if Taxonomy.any? %>
            <%= render "admin/services/editors/taxonomies", s: s %>
          <% else %>
            <p>
              No taxonomies set up yet.
              <%= link_to 'Create some taxonomies', admin_taxonomies_path %>
            </p>
          <% end %>
        <% end %>

        <%= render "shared/collapsible", name: "Locations", count: @service.locations.length, id: "locations-editor", help_text: "Provide locations where this service can be used. For a fully remote or virtual service, leave this blank." do %>
        <%= render "admin/services/editors/locations", s: s %>
        <% end %>

        <%= render "shared/collapsible", name: "Fees", count: @service.cost_options.length, id: "fees-editor" do %>
        <%= render "admin/services/editors/cost-options", s: s %>
        <% end %>

        <%= render "shared/collapsible", name: "Local offer and SEND", id: "local-offer-editor" do %>
        <%= render "admin/services/editors/local-offer", s: s %>
        <% end %>

        <%= render "shared/collapsible", name: "Suitable for", id: "suitabilities-editor" do %>
        <%= render "admin/services/editors/suitabilities", s: s %>
        <% end %>

        <%= render "shared/collapsible", name: "Scheduling", count: @service.regular_schedules.length, id: "schedule-editor", help_text: "Build a set of regular opening times for the service." do %>
        <%= render "admin/services/editors/regular-schedule", s: s %>
        <% end %>

        <%= render "shared/collapsible", name: "Links", id: "social-media-editor" do %>
        <%= render "admin/services/editors/links", s: s %>
        <% end %>

        <%= render "shared/collapsible", name: "Ages", id: "visibility-editor" do %>
        <%= render "admin/services/editors/ages", s: s %>
        <% end %>

        <%= render "shared/collapsible", name: "Visibility", id: "visibility-editor", help_text: "Control if and when the service is listed in public search results." do %>
        <%= render "admin/services/editors/dates", s: s %>
        <% end %>

        <%= render "shared/collapsible", name: "Labels", count: @service.label_list.length, id: "labels-editor", help_text: "Use labels to group services together in whatever way you need." do %>
        <%= render "admin/services/editors/labels", s: s %>
        <% end %>

        <%= render "shared/collapsible", name: "Custom fields", id: "custom-fields-editor" do %>
          <% if CustomField.any? %>
            <%= render "admin/services/editors/custom-fields", s: s %>
          <% else %>
            <p>
              No custom fields set up yet.
              <%= link_to 'Create some custom fields', admin_custom_field_sections_path %>
            </p>
          <% end %>
        <% end %>

        <div class="form-actions">
            <%= s.submit "Create", class: "button" %>
        </div>

        <% end %>
    </div>

</div>

app/views/admin/services/show.html.erb
<% content_for :title do %>
  <%= @service.name %> | 
<% end %>

<% content_for :header do %>
    <%= render "notices" %>
    <%= render "shared/dynamic-back-link", text: "Back to services", path: admin_services_path %>
    <div class="page-header__actions">
      <h1 class="page-header__title two-thirds"><%= @service.display_name %></h1>
    </div>
<% end %>

<header class="actions">
  <%= render "shared/watch" %>
  <button class="inline-button actions__pull-right" data-open-all>Open all</button>
  <button class="inline-button" data-close-all>Close all</button>
</header>

<div class="with-sidebar">

  <div>
    <%= form_for(@service, as: :service, url: admin_service_path(@service), method: :put, data: {warn_unsaved_changes: true}, builder: OutpostFormBuilder) do |s| %>

      <%= render "shared/errors", model: @service %>

      <%= render "shared/collapsible", name: "Basics", id: "basic-info-editor" do %>
        <%= render "admin/services/editors/basics", s: s %>
      <% end %>

      <% if Directory.any? %>
        <%= render "shared/collapsible", name: "Directories", count: @service.directories&.length, id: "directories-editor", help_text: "Select which directories you want the service to appear in" do %>
          <%= render "admin/services/editors/directories", s: s %>
        <% end %>
      <% end %>

      <%= render "shared/collapsible", name: "Taxonomies", count: @service.taxonomies.length, id: "taxonomy-editor", help_text: "Help users understand what kind of service this is." do %>
        <% if Taxonomy.any? %>
          <%= render "admin/services/editors/taxonomies", s: s %>
        <% else %>
          <p>
            No taxonomies set up yet.
            <% if current_user.can_edit_taxonomies %>
              <%= link_to 'Create some taxonomies', admin_taxonomies_path %>
            <% end %>
          </p>
        <% end %>
      <% end %>

      <%= render "shared/collapsible", name: "Contacts", count: @service.contacts.length, id: "contacts-editor", help_text: "Provide individual points of contact for users." do %>
        <%= render "admin/services/editors/contacts", s: s %>
      <% end %>

      <%= render "shared/collapsible", name: "Locations", count: @service.locations.length, id: "locations-editor", help_text: "Provide locations where this service can be used. For a fully remote or virtual service, leave this blank." do %>
        <%= render "admin/services/editors/locations", s: s %>
      <% end %>

      <%= render "shared/collapsible", name: "Fees", count: @service.cost_options.length, id: "fees-editor" do %>
        <%= render "admin/services/editors/cost-options", s: s %>
      <% end %>

      <%= render "shared/collapsible", name: "Opening times", count: @service.regular_schedules.length, id: "schedule-editor", help_text: "Build a set of regular opening times for the service." do %>
        <%= render "admin/services/editors/regular-schedule", s: s %>
      <% end %>

      <%= render "shared/collapsible", name: "Links", count: @service.links.length, id: "links-editor" do %>
        <%= render "admin/services/editors/links", s: s %>
      <% end %>

      <%= render "shared/collapsible", name: "Local offer and SEND", id: "local-offer-editor" do %>
        <%= render "admin/services/editors/local-offer", s: s %>
      <% end %>

      <%= render "shared/collapsible", name: "Suitable for", id: "suitability-editor" do %>
        <%= render "admin/services/editors/suitabilities", s: s %>
      <% end %>

      <%= render "shared/collapsible", name: "Ages", id: "ages-editor" do %>
        <%= render "admin/services/editors/ages", s: s %>
      <% end %>

      <%= render "shared/collapsible", name: "Visibility", id: "visibility-editor", help_text: "Control if and when the service is listed in public search results." do %>
        <%= render "admin/services/editors/dates", s: s %>
      <% end %>
 
      <%= render "shared/collapsible", name: "Labels", count: @service.label_list.length, id: "labels-editor", help_text: "Use labels to group services together in whatever way you need." do %>
        <%= render "admin/services/editors/labels", s: s %>
      <% end %>

      <%= render "shared/collapsible", name: "Custom fields", id: "custom-fields-editor" do %>
        <% if CustomField.any? %>
          <%= render "admin/services/editors/custom-fields", s: s %>
        <% else %>
          <p>
            No custom fields set up yet.
            <% if current_user.can_edit_custom_fields %>
              <%= link_to 'Create some custom fields', admin_custom_field_sections_path %>
            <% end %>
          </p>
        <% end %>
      <% end %>

      <%= render "admin/services/permenant-deletion", s: s %>

      <div class="form-actions">
        <%= s.submit "Update", class: "button" %>
        <% unless @service.discarded? %>
          <%= link_to "Archive", admin_service_path(@service), method: "delete", class: "button button--danger", data: {confirm: "Are you sure?" } %>
        <% end %>
      </div>

    <% end %>
  </div>

  <aside class="with-sidebar__sidebar">
  
      <% if @service.ofsted_item %>
        <div class="dark-panel">
          <p>This service is linked to <strong><%= link_to "an Ofsted feed item", admin_ofsted_path(@service.ofsted_item) %></strong></p>
        </div>
      <% end %>

      <%= render "shared/collapsible", name: "History", id: "service-history" do %>
        <%= link_to "Compare versions", admin_service_versions_path(@service), class: "collapsible__action" %>
        <%= render "shared/version-tree", object: @service %>
      <% end %>

      <%= render "admin/services/notes" %>
      <%= render "admin/services/feedback" %>
  </aside>

</div>