config/routes.rb
Rails.application.routes.draw do
  
  root "organisations#index"

  use_doorkeeper
  devise_for :users, :controllers => { registrations: 'registrations' }
  devise_scope :user do
    get "login", to: "devise/sessions#new"
    get "register", to: "devise/registrations#new"
  end
  
  # community users
  resources :organisations, only: [:index, :new, :create, :edit, :update]
  resources :services, except: [:index] do
    post "confirmation", to: "services#confirmation"
    resources :feedback, only: [:index, :create]
  end
  
  # https://trello.com/c/aFtIf3QZ/242-prevent-community-users-from-managing-users-in-their-organisation
  # resources :members, only: [:new, :create, :destroy]

  # admin users
  namespace :admin do
    root "dashboard#index"
    resources :services, except: :edit do
      resources :watch, only: [:create, :destroy]
      resources :notes, only: [:create, :destroy]
      resources :versions, only: [:index]
      collection do 
        resources :archive, only: [:update]
        resources :requests, only: [:index, :update]
      end
    end
    resources :organisations, except: :edit do
      get "timetable", to: "organisations#timetable"
    end
    resources :labels, only: [:index, :destroy]
    resources :locations, except: [:edit, :new, :create]
    resources :taxonomies, except: [:new, :edit]
    resources :feedbacks, only: [:index]
    resources :ofsted, only: [:index, :show] do
      put "dismiss"
      get "versions"
      collection do
        get "pending"
      end
    end
    resources :activity, only: [:index, :show]
    resources :custom_field_sections, except: [:edit]
    resources :users, except: [:edit] do
      post :reset, on: :member
      put :reactivate, on: :member
    end
    resource :settings, only: [:edit, :update]
    resources :send_needs, except: [:edit, :show, :destroy, :update] do
      collection do
        post 'create_defaults', to: "send_needs#create_defaults"
      end
    end
    resources :accessibilities, except: [:edit, :show, :destroy, :update] do
      collection do
        post 'create_defaults', to: "accessibilities#create_defaults"
      end
    end
    resources :suitabilities, except: [:edit, :show, :destroy, :update] do
      collection do
        post 'create_defaults', to: "suitabilities#create_defaults"
      end
    end
  end

  # api
  namespace :api do
    namespace :v1 do
      resources :taxonomies, only: [:index]
      resources :send_needs, only: [:index]
      resources :suitabilities, only: [:index]
      resources :accessibilities, only: [:index]
      get "me", to: "me#show"
      resources :services, only: [:index, :show]
    end
  end

end

app/views/shared/_collapsible.html.erb
<div class="collapsible" id="<%= id %>">
    <button class="collapsible__header" type="button">
        <h2>
            <%= name %>
            <% if defined?(count) %>
                <span class="collapsible__header-count">(<%= count %>)</span>
            <% end %>
        </h2>
    </button>
    <% if defined?(help_text) %>
        <button class="help-button" type="button" data-tippy-content="<%= help_text %>">Help with this section</button>
    <% end %>
    <div class="collapsible__content">
        <%= yield %>
    </div>
</div>

app/views/shared/_directory-shortcuts.html.erb
<nav class="shortcuts shortcuts--no-bottom-spacing">

  <%= render partial: "shared/shortcuts_item", 
    locals: {
      state: all_state,
      link: all_link,
      count: all_count,
      label: all_label,
    } %>

  <% if Directory.any? %>
    <span class="shortcuts__divider">|</span>

    <% Directory.all.each_with_index do |directory, index| %>

      <%= render partial: "shared/shortcuts_item",
        locals: {
          state: params[:directory] === directory.name,
          link: directory_links[directory.name],
          count: directory_counts.dig(directory.name, :all),
          label: directory.name
        } %>

      <% if index != Directory.all.size-1 %>
        <span class="shortcuts__divider">|</span>
      <% end %>
    <% end %>
    <br />
  <% end %>

</nav>

app/views/shared/_head.html.erb
<head>
    <title>
        <%= yield :title %> <%= Setting.outpost_title %> | <%= Setting.outpost_sub_title %>
    </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta http-equiv="X-UA-Compatible" content="IE=10">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'shared/settings' %>
</head>

app/views/shared/_header.html.erb
<%= render "shared/env-banner" %>
<header class="site-header <%= "site-header--logged-out" unless user_signed_in? %> <%= 'light' if is_text_dark(Setting.primary_color)  %>">
    <div class="<%= "container" unless full_width %> site-header__inner">
        <div class="site-header__masthead">
            <div class="site-header__logo-link">
            <% if FileUpload.find_by(var: 'outpost_logo') %>
            <%= image_tag(url_for(FileUpload.find_by(var: 'outpost_logo').file), alt: Setting.outpost_title, class: "site-header__logo") %>
            <% else %>
            <%= image_tag("logo-outpost.svg", alt: "Outpost", class: "site-header__logo") %>
            <% end %>
            </div>
        </div>

        
        <% if user_signed_in? %>
        <div class="site-header__actions">
            <% if ENV["INSTANCE"].present? && ENV["INSTANCE"] === 'buckinghamshire' %>
                <%= render "shared/app-switcher" %>
            <% end %>
            <%= link_to current_user.display_name, edit_user_registration_path, class: "site-header__username"%>
            <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "site-header__link" %>
        </div>
        <% end %>


        <nav class="site-header__service-name-holder">
            <%= link_to Setting.outpost_title, root_path, class: "site-header__service-name"%>
            <% if current_user && current_user.admin? %>
            <strong class="site-header__phase-tag">Beta</strong>
            <% end %>
        </nav>
    </div>
</header>

app/views/shared/_navigation.html.erb
<% if user_signed_in? && current_user.admin? %>
    <nav class="site-nav">
        <div class="site-nav__inner <%= "container" unless full_width %>">

                <%= link_to_unless_current "Dashboard", admin_root_path, class: "site-nav__link" do %>
                    <span class="site-nav__current">Dashboard</span>
                <% end %>
                
                <div class="site-nav__submenu-holder site-nav__submenu-holder--with-badge">
                    <%= link_to_unless_current "Services", admin_services_path, class: "site-nav__link" do %>
                        <span class="site-nav__current" tabindex="0">Services</span>
                    <% end %>
                    <% if @service_counts.dig(:all, :pending) > 0 %>
                        <div class="badge"><%= @service_counts.dig(:all, :pending) %></div>
                    <% end %>
                
                    <ul class="site-nav__submenu">
                        <li class="site-nav__submenu-item">
                            <%= link_to_unless_current "Organisations", admin_organisations_path, class: "site-nav__submenu-link" do %>
                                <span class="site-nav__submenu-current">Organisations</span>
                            <% end %>
                        </li>
                        <li class="site-nav__submenu-item">
                            <%= link_to_unless_current "Locations", admin_locations_path, class: "site-nav__submenu-link" do %>
                                <span class="site-nav__submenu-current">Locations</span>
                            <% end %>
                        </li>
                        
                        <% if current_user.can_edit_taxonomies %>
                            <li class="site-nav__submenu-item">
                                <%= link_to_unless_current "Taxonomies", admin_taxonomies_path, class: "site-nav__submenu-link" do %>
                                    <span class="site-nav__submenu-current">Taxonomies</span>
                                <% end %>
                            </li>
                        <% end %>

                        <li class="site-nav__submenu-item">
                            <%= link_to_unless_current "Feedback", admin_feedbacks_path, class: "site-nav__submenu-link" do %>
                                <span class="site-nav__submenu-current">Feedback</span>
                            <% end %>
                        </li>
                        <li class="site-nav__submenu-item">
                            <%= link_to_unless_current "Labels", admin_labels_path, class: "site-nav__submenu-link" do %>
                                <span class="site-nav__submenu-current">Labels</span>
                            <% end %>
                        </li>

                        <% if current_user.can_edit_custom_fields %>
                            <li class="site-nav__submenu-item">
                                <%= link_to_unless_current "Custom fields", admin_custom_field_sections_path, class: "site-nav__submenu-link" do %>
                                    <span class="site-nav__submenu-current">Custom fields</span>
                                <% end %>
                            </li>
                        <% end %>

                    </ul>
                </div>

                <%= link_to_unless_current "Activity", admin_activity_index_path, class: "site-nav__link" do %>
                    <span class="site-nav__current">Activity</span>
                <% end %>

                <%= link_to_unless_current "Users", admin_users_path, class: "site-nav__link" do %>
                    <span class="site-nav__current">Users</span>
                <% end %>

                

                <% if current_user.admin_users? %>
                <div class="site-nav__submenu-holder site-nav__submenu-holder--with-badge">
                    <% if current_user.superadmin? %>
                        <%= link_to_unless_current "Settings", edit_admin_settings_path, class: "site-nav__link" do %>
                            <span class="site-nav__current">Settings</span>
                        <% end %>
                    <% else %>
                        <span class="site-nav__link">Settings</span>
                    <% end %>
                
                    <ul class="site-nav__submenu">
                        <li class="site-nav__submenu-item">
                            <%= link_to_unless_current "SEND Needs", admin_send_needs_path, class: "site-nav__submenu-link" do %>
                                <span class="site-nav__submenu-current">SEND Needs</span>
                            <% end %>
                        </li>
                        <li class="site-nav__submenu-item">
                            <%= link_to_unless_current "Accessibilities", admin_accessibilities_path, class: "site-nav__submenu-link" do %>
                                <span class="site-nav__submenu-current">Accessibilities</span>
                            <% end %>
                        </li>
                        <li class="site-nav__submenu-item">
                            <%= link_to_unless_current "Suitabilities", admin_suitabilities_path, class: "site-nav__submenu-link" do %>
                                <span class="site-nav__submenu-current">Suitabilities</span>
                            <% end %>
                        </li>
                    </ul>
                </div>
                <% end %>


                <% if current_user.admin_ofsted? %>
                    <div class="site-nav__pull-right">
                        <%= link_to_unless_current "Ofsted feed", admin_ofsted_index_path, class: "site-nav__link" do %>
                            <span class="site-nav__current site-nav--pull-right">Ofsted feed </span>
                        <% end %>
                        <% if @ofsted_counts.dig(:all, :pending) > 0 %>
                            <div class="badge"><%= @ofsted_counts.dig(:all, :pending) %></div>
                        <% end %>
                    </div>
                <% end %>
        </div>
    </nav>
<% end %>

app/views/shared/_notes.html.erb
<section class="collapsible" id="notes">
  <button class="collapsible__header" aria-expanded="true">
    <h2>Notes <span class="collapsible__header-count">(<%= @service.notes.length %>)</span></h2>
  </button>
  <div class="collapsible__content">

    <div class="notes-list">
      <% if @service.notes.present? %>
        <% @service.notes.each do |n| %>
          <article class="notes-list__note">
            <header class="notes-list__note-header">
              <strong><%= render "shared/poppables/user", u: n.user %></strong> 
              | <%= time_ago_in_words(n.created_at).humanize %> ago 
              <% if n.user === current_user %>| <%= link_to "Remove", admin_service_note_path(@service, n), method: "delete", data: {confirm: "Are you sure you want to remove this note?"} %><% end %>
            </header>
            <p><%= n.body %></p>
          </article>
        <% end %>
      <% end %>
    </div>

    <%= form_for [:admin, @service, @service.notes.new] do |f| %>
        <div class="field">
            <%= f.label :body, class: "visually-hidden" %>
            <%= f.text_area :body , class: "field__input", placeholder: "Type a note...", maxlength: 200, required: true %>
        </div>
        <%= f.button "Add note", class: "button button--small"%>
    <% end %>

  </div>
</section>

app/views/shared/_preview-canvas.html.erb
<div class="snapshot-preview__canvas">
    <% combined_keys = live.merge(version).except!(*ignorable_fields).keys %>

    <% combined_keys.each do |key| %>
        <h4 class="snapshot-preview__label"><%= key.humanize %></h4>
    
        <% if version.has_key?(key) && live.has_key?(key) %>

            <%= diff(version[key], live[key]) %>

        <% elsif live.has_key?(key) %>

            <%= diff("", live[key]) %>

        <% elsif version.has_key?(key) %>

            <%= diff(version[key], "") %>
            
        <% end %>

    <% end %>
</div>

app/views/shared/_services-nav.html.erb
<% 
  @directory_links = {}

  Directory.all.each do |directory|
    @directory_links[directory.name] = admin_services_path(directory: directory.name);
  end
%>

<%=
  # display the directory headings
  render partial: "shared/directory-shortcuts",  locals: { 
    all_state: !params[:directory].present?,
    all_link: admin_services_path,
    all_count: @service_counts.dig(:all, :all),
    all_label: "All",
    directory_links: @directory_links,
    directory_counts: @service_counts
  }
%>

<nav class="shortcuts shortcuts--no-top-spacing  shortcuts--sublevel">

  <%= render partial: "shared/shortcuts_item",
    locals: {
      state: params[:ofsted] === "true",
      link: admin_services_path(directory: params[:directory], ofsted: true),
      count: !params[:directory].present? ? @service_counts.dig(:all, :ofsted) : @service_counts[params[:directory]][:ofsted],
      label: "Ofsted registered"
    } %>

  <%= render partial: "shared/shortcuts_item",
    locals: {
      state: current_page?({controller: 'admin/requests', action: 'index'}),
      link: admin_requests_path(directory: params[:directory]),
      count: !params[:directory].present? ? @service_counts.dig(:all, :pending) : @service_counts[params[:directory]][:pending],
      label: "Pending"
    } %>

  <%= render partial: "shared/shortcuts_item",
    locals: {
      state: params[:archived] === "true",
      link: admin_services_path(directory: params[:directory], archived: true),
      count: !params[:directory].present? ? @service_counts.dig(:all, :archived) :  @service_counts[params[:directory]][:archived],
      label: "Archived"
    } %>

</nav>

app/views/shared/_settings.html.erb
<style type="text/css">
<% if Setting.primary_color.present? %>
  :root {
    --primary: <%= Setting.primary_color %>;
  }
<% end %>

<% if Setting.outpost_logo_height_mobile.present? && Setting.outpost_logo_height_mobile =~ /\A\d+\z/ %>
  .site-header {
    --site-header-logo-height-mobile: <%= Setting.outpost_logo_height_mobile %>px;
  }
<% end %>

<% if Setting.outpost_logo_height.present? && Setting.outpost_logo_height =~ /\A\d+\z/ %>
  .site-header {
    --site-header-logo-height: <%= Setting.outpost_logo_height %>px;
  }
<% end %>
</style>

app/views/shared/_shortcuts_item.erb
<span class="shortcuts__item <%= state ? 'current' : '' %>">
    <%= link_to label, link, class: "shortcuts__link" %>
    <span class="shortcuts__count">(<%= count %>)</span>
</span>

app/views/shared/_taxonomies-nav.html.erb
<% 
    @directory_links = {}

    if Directory.any?
      Directory.all.each do |directory|
        @directory_links[directory.name] = admin_taxonomies_path(directory: directory.name);
      end
    end
%>
    
<%= 
  # display the directory headings
  render partial: "shared/directory-shortcuts",  locals: { 
        all_state: !params[:directory].present?,
        all_link: admin_taxonomies_path,
        all_count: @taxonomy_counts.dig(:all, :all),
        all_label: "All",
        directory_links: @directory_links,
        directory_counts: @taxonomy_counts
  }
%>

app/views/shared/_user-circle.html.erb
<div aria-hidden="true" class="user-circle">
    <%= u.initials %>
    <% if u.last_seen && u.last_seen > (Time.now - 10.minutes) %>
        <div class="user-circle__active" title="Active"></div>
    <% end %>
</div>

app/views/shared/_users-nav.html.erb
<% 
    @directory_links = {}

    Directory.all.each do |directory|
      @directory_links[directory.name] = admin_users_path(directory: directory.name);
    end

%>

<%= 
    # display the directory headings
    render partial: "shared/directory-shortcuts",  locals: { 
        all_state: !params[:directory].present?,
        all_link: admin_users_path,
        all_count: @user_counts.dig(:all, :all),
        all_label: "All",
        directory_links: @directory_links,
        directory_counts: @user_counts
  }
%>
     
<nav class="shortcuts shortcuts--no-top-spacing  shortcuts--sublevel">

    <% 

    # toggle the active state for the active/deactivated filters
    if params[:deactivated].present? && params[:deactivated] === "true" 
        @sublevel_active_state = false;
        @sublevel_deactivated_state = true;
    elsif params[:deactivated].present? && params[:deactivated] === "false"
        @sublevel_active_state = true;
        @sublevel_deactivated_state = false;
    end

    # decide what the urls will be like for the active/deactivated links
    @sublevel_active_inactive_link = admin_users_path(directory: params[:directory], deactivated: false);
    @sublevel_deactivated_inactive_link = admin_users_path(directory: params[:directory], deactivated: true);


    # decide what the counts will be for the active/deactivated links
    if !params[:directory].present? 
        @sublevel_active_count = @user_counts.dig(:all, :active);
        @sublevel_deactivated_count  = @user_counts.dig(:all, :deactivated);
    elsif
        @sublevel_active_count = @user_counts.dig(params[:directory], :active);
        @sublevel_deactivated_count  = @user_counts.dig(params[:directory], :deactivated);
    end

    %>   

     <%= render partial: "shared/shortcuts_item", 
     locals: {
        state: @sublevel_active_state, 
        link: @sublevel_active_inactive_link, 
        count: @sublevel_active_count,
        label: "Active"
      } %>
     
     <%= render partial: "shared/shortcuts_item", 
     locals: {
        state: @sublevel_deactivated_state, 
        link: @sublevel_deactivated_inactive_link, 
        count: @sublevel_deactivated_count,
        label: "Deactivated"
      } %>
     


</nav>

app/views/shared/_version-tree.html.erb
<% if @versions.present? %>
  <ul class="stepper <%= "stepper--summarised" if object.versions.length > 4 %>">
    <% @versions.each do |v| %>
      <li class="stepper__step <%= stepper_class(v.event) %>">
        <div>
          <%= pretty_event(v.event)&.humanize %>
          <% if v.user.present? %>
            by <strong><%= render "shared/poppables/user", u: v.user %></strong>
          <% elsif v.whodunnit.present? %>
            by <strong><%= render "shared/poppables/deleted_user", u: v.whodunnit %></strong>
          <% else %>
            by system
          <% end %>
        </div>
        <p class="stepper__time">
        <%= time_ago_in_words(v.created_at).humanize %> ago
        </p>
      </li>
    <% end %>
  </ul>
<% else %>
  <p class="no-results">No versions to show</p>
<% end %>