config/routes.rb
Rails.application.routes.draw do
  
  root "organisations#index"

  use_doorkeeper
  devise_for :users, :controllers => { registrations: 'registrations' }
  devise_scope :user do
    get "login", to: "devise/sessions#new"
    get "register", to: "devise/registrations#new"
  end
  
  # community users
  resources :organisations, only: [:index, :new, :create, :edit, :update]
  resources :services, except: [:index] do
    post "confirmation", to: "services#confirmation"
    resources :feedback, only: [:index, :create]
  end
  
  # https://trello.com/c/aFtIf3QZ/242-prevent-community-users-from-managing-users-in-their-organisation
  # resources :members, only: [:new, :create, :destroy]

  # admin users
  namespace :admin do
    root "dashboard#index"
    resources :services, except: :edit do
      resources :watch, only: [:create, :destroy]
      resources :notes, only: [:create, :destroy]
      resources :versions, only: [:index]
      collection do 
        resources :archive, only: [:update]
        resources :requests, only: [:index, :update]
      end
    end
    resources :organisations, except: :edit do
      get "timetable", to: "organisations#timetable"
    end
    resources :labels, only: [:index, :destroy]
    resources :locations, except: [:edit, :new, :create]
    resources :taxonomies, except: [:new, :edit]
    resources :feedbacks, only: [:index]
    resources :ofsted, only: [:index, :show] do
      put "dismiss"
      get "versions"
      collection do
        get "pending"
      end
    end
    resources :activity, only: [:index, :show]
    resources :custom_field_sections, except: [:edit]
    resources :users, except: [:edit] do
      post :reset, on: :member
      put :reactivate, on: :member
    end
    resource :settings, only: [:edit, :update]
    resources :send_needs, except: [:edit, :show, :destroy, :update] do
      collection do
        post 'create_defaults', to: "send_needs#create_defaults"
      end
    end
    resources :accessibilities, except: [:edit, :show, :destroy, :update] do
      collection do
        post 'create_defaults', to: "accessibilities#create_defaults"
      end
    end
    resources :suitabilities, except: [:edit, :show, :destroy, :update] do
      collection do
        post 'create_defaults', to: "suitabilities#create_defaults"
      end
    end
  end

  # api
  namespace :api do
    namespace :v1 do
      resources :taxonomies, only: [:index]
      resources :send_needs, only: [:index]
      resources :suitabilities, only: [:index]
      resources :accessibilities, only: [:index]
      get "me", to: "me#show"
      resources :services, only: [:index, :show]
    end
  end

end

app/models/custom_field_section.rb
class CustomFieldSection < ApplicationRecord
    validates :name, presence: true, uniqueness: true

    has_many :custom_fields, -> { order(created_at: :asc) }
    accepts_nested_attributes_for :custom_fields, allow_destroy: true, reject_if: :all_blank

    default_scope { order(sort_order: :asc) }

    scope :visible_to, -> (current_user){ current_user.admin ? all : where(public: true) }
end

app/controllers/admin/custom_field_sections_controller.rb
class Admin::CustomFieldSectionsController < Admin::BaseController
  before_action :user_admins_only
  before_action :set_section, only: [:show, :update, :destroy]

  def index
    @sections = CustomFieldSection.includes(:custom_fields).all
  end

  def new
    @section = CustomFieldSection.new
  end

  def create
    @section = CustomFieldSection.new(custom_field_section_params)
    if @section.save
      redirect_to admin_custom_field_sections_path, notice: "Fields have been created."
    else
      render "new"
    end
  end

  def show
  end

  def update
    if @section.update(custom_field_section_params)
      redirect_to admin_custom_field_section_path(@section), notice: "Fields have been updated."
    else
      render "show"
    end
  end

  def destroy
    @section.destroy
    redirect_to admin_custom_field_sections_path, notice: "Those fields has been removed."
  end

  private

  def set_section
    @section = CustomFieldSection.find(params[:id])
  end

  def custom_field_section_params
      params.require(:custom_field_section).permit(
        :name,
        :hint,
        :public,
        :api_public,
        :sort_order,
        custom_fields_attributes: [
          :id,
          :key,
          :field_type,
          :hint,
          :options,
          :_destroy
        ]
      )
  end

end

app/views/admin/custom_field_sections/_fields.html.erb
<div class="field field--required">
    <%= f.label :name, "Name", class: "field__label" %>
    <p class="field__hint">A word or short phrase that all users will understand.</p>
    <%= f.text_field :name, class: "field__input" %>
</div>

<div class="field">
    <%= f.label :hint, "Instructions", class: "field__label" %>
    <p class="field__hint">Keep this brief. A few words or a short sentence is enough.</p>
    <%= f.text_area :hint, class: "field__input", rows: 2 %>
</div>

<div class="field">
    <%= f.label :sort_order, class: "field__label" %>
    <p class="field__hint">Override the default sort order. Higher is later.</p>
    <%= f.number_field :sort_order, class: "field__input one-half" %>
</div>

<div class="field checkbox">
    <%= f.check_box :public, class: "checkbox__input"%>
    <%= f.label :public, class: "checkbox__label" do %>
        Visible to community users?
        <button class="help-button help-button--small" type="button" data-tippy-content="If checked, all fields in this section can be seen and edited by residents.">What does this mean?</button>
    <% end %>
</div>

<div class="field checkbox">
    <%= f.check_box :api_public, class: "checkbox__input"%>
    <%= f.label :api_public, class: "checkbox__label" do %>
        Expose in public API?
        <button class="help-button help-button--small" type="button" data-tippy-content="If checked, all fields in this section may be made visible in API clients.">What does this mean?</button>
    <% end %>
</div>

<% if params[:action] != 'new'  %>

<h2 class="page-subheading">Fields</h2>
<section class="repeater">
    <ul class="repeater__panels" aria-live="polite">
        <%= f.fields_for :custom_fields do |c| %>
            <li class="repeater__panel" data-custom-fields>
                <%= render "admin/custom_field_sections/repeatable-fields", c: c %>
            </li>
        <% end %>
    </ul>

    <%= link_to_add_fields "Add a field", f, :custom_fields, "admin/custom_field_sections/repeatable-fields" %>
</section>

 <% end %>

app/views/admin/custom_field_sections/_repeatable-fields.html.erb
<div class="field-group field-group--two-cols">
    <div class="field field--required">
        <%= c.label :key, "Label", class: "field__label" %>
        <%= c.text_field :key, class: "field__input" %>
    </div>

    <div class="field field--required">
        <%= c.label :field_type, "Field type", class: "field__label" %>
        <%= c.select :field_type, CustomField.types.collect { |t| [t, t.parameterize]}, {}, class: "field__input", data: { type: true } %>
    </div>
</div>

<div class="field" data-options>
    <%= c.label :options, "Options", class: "field__label" %>
    <%= c.text_field :options, class: "field__input", data: { labels: true } %>
</div>

<div class="field">
    <%= c.label :hint, "Instructions", class: "field__label" %>
    <%= c.text_area :hint, class: "field__input", rows: 1 %>
</div>

<%= c.hidden_field :_destroy,  data: {destroy_field: true} %>

<button type="button" class="repeater__closer" data-close="true" title="Remove this field">Remove this field</button>

app/views/admin/custom_field_sections/index.html.erb
<% content_for :title do %>Custom fields | <% end %>

<% content_for :header do %>
    <%= link_to "Back to services", admin_services_path, class: "go-back" %>
    <h1 class="page-header__title">Custom fields</h1>
<% end %>

<header class="actions">
  <%= link_to "Add section", new_admin_custom_field_section_path, class: "button button--small button--add" %>
</header>

<% if @sections.present? %>
  <table>
    <thead>
      <th>Name</th>
      <th>Fields</th>
      <th>Visible to community users</th>
      <th>Exposed in API</th>
      <th>Sort order</th>
    </thead>
    <tbody>
      <% @sections.each do |s| %>
        <tr>
          <td><%= link_to s.name, admin_custom_field_section_path(s) %></td>
          <td><%= s.custom_fields.map{ |f| f.key }.join(", ") %></td>
          <td>
            <% if s.public %>
              <%= image_tag "tick-black.svg", alt: "Yes" %>
            <% else %>
              —
            <% end %>
          </td>
          <td>
            <% if s.api_public %>
              <%= image_tag "tick-black.svg", alt: "Yes" %>
            <% else %>
              —
            <% end %>
          </td>
          <td><%= s.sort_order %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p class="no-results no-results--big">No fields have been set up</p>
<% end %>

app/views/admin/custom_field_sections/new.html.erb
<% content_for :header do %>
    <%= render "shared/dynamic-back-link", text: "Back to custom fields", path: admin_custom_field_sections_path %>
    <h1 class="page-header__title">Add a new section</h1>
<% end %>

<%= form_for @section, url: admin_custom_field_sections_path, html: {class: "two-thirds"}, data: {warn_unsaved_changes: true} do |f| %>
    <%= render "shared/errors", model: @section %>
    
    <%= render "admin/custom_field_sections/fields", f: f %>

    <div class="form-actions">
        <%= f.button "Create", class: "button" %>
    </div>
<% end %>

app/views/admin/custom_field_sections/show.html.erb
<% content_for :header do %>
    <%= render "shared/dynamic-back-link", text: "Back to custom fields", path: admin_custom_field_sections_path %>
    <h1 class="page-header__title"><%= @section.name %></h1>
<% end %>

<%= form_for @section, url: admin_custom_field_section_path, html: {class: "two-thirds"}, data: {warn_unsaved_changes: true} do |f| %>
    <%= render "shared/errors", model: @section %>
    
    <%= render "admin/custom_field_sections/fields", f: f %>

    <div class="form-actions">
        <%= f.button "Update", class: "button" %>
        <%= link_to "Remove", admin_custom_field_section_path(@section), method: "delete", class: "button button--danger", data: {confirm: "Are you sure? Data in these fields will become invisible." } %>
    </div>
<% end %>