config/routes.rb
Rails.application.routes.draw do
  
  root "organisations#index"

  use_doorkeeper
  devise_for :users, :controllers => { registrations: 'registrations' }
  devise_scope :user do
    get "login", to: "devise/sessions#new"
    get "register", to: "devise/registrations#new"
  end
  
  # community users
  resources :organisations, only: [:index, :new, :create, :edit, :update]
  resources :services, except: [:index] do
    post "confirmation", to: "services#confirmation"
    resources :feedback, only: [:index, :create]
  end
  
  # https://trello.com/c/aFtIf3QZ/242-prevent-community-users-from-managing-users-in-their-organisation
  # resources :members, only: [:new, :create, :destroy]

  # admin users
  namespace :admin do
    root "dashboard#index"
    resources :services, except: :edit do
      resources :watch, only: [:create, :destroy]
      resources :notes, only: [:create, :destroy]
      resources :versions, only: [:index]
      collection do 
        resources :archive, only: [:update]
        resources :requests, only: [:index, :update]
      end
    end
    resources :organisations, except: :edit do
      get "timetable", to: "organisations#timetable"
    end
    resources :labels, only: [:index, :destroy]
    resources :locations, except: [:edit, :new, :create]
    resources :taxonomies, except: [:new, :edit]
    resources :feedbacks, only: [:index]
    resources :ofsted, only: [:index, :show] do
      put "dismiss"
      get "versions"
      collection do
        get "pending"
      end
    end
    resources :activity, only: [:index, :show]
    resources :custom_field_sections, except: [:edit]
    resources :users, except: [:edit] do
      post :reset, on: :member
      put :reactivate, on: :member
    end
    resource :settings, only: [:edit, :update]
    resources :send_needs, except: [:edit, :show, :destroy, :update] do
      collection do
        post 'create_defaults', to: "send_needs#create_defaults"
      end
    end
    resources :accessibilities, except: [:edit, :show, :destroy, :update] do
      collection do
        post 'create_defaults', to: "accessibilities#create_defaults"
      end
    end
    resources :suitabilities, except: [:edit, :show, :destroy, :update] do
      collection do
        post 'create_defaults', to: "suitabilities#create_defaults"
      end
    end
  end

  # api
  namespace :api do
    namespace :v1 do
      resources :taxonomies, only: [:index]
      resources :send_needs, only: [:index]
      resources :suitabilities, only: [:index]
      resources :accessibilities, only: [:index]
      get "me", to: "me#show"
      resources :services, only: [:index, :show]
    end
  end

end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :service

  validates_presence_of :topic
  validates_presence_of :body  

  after_save :notify_owners

  paginates_per 20

  def notify_owners
    self.service.organisation.users.kept.each do |user|
      ServiceMailer.with(feedback: self, service: self.service, user: user).notify_owner_of_feedback_email.deliver_later
    end
  end
end

app/controllers/admin/feedbacks_controller.rb
class Admin::FeedbacksController < Admin::BaseController
    def index
        @feedbacks = Feedback.order(created_at: :desc).includes(:service).page(params[:page])
    end
end

app/controllers/feedback_controller.rb
# This controller lets community users and anonymous (logged-out) users submit
# feedback on a service.
class FeedbackController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_service
  before_action :redirect_if_admin!

  def index
    @feedback = @service.feedbacks.new
  end

  def create
    @feedback = @service.feedbacks.build(feedback_params)
    if @feedback.save
      render "create"
    else
      render "index"
    end
  end

  private

  def set_service
    @service = Service.find(params[:service_id])
  end

  def redirect_if_admin!
    redirect_to admin_service_path(@service) if current_user&.admin?
  end

  def feedback_params
    params.require(:feedback).permit(
      :body,
      :topic
    )
  end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
    skip_before_action :authenticate_user!
    before_action :no_admins
    before_action :set_service

    def index
        @feedback = @service.feedbacks.new
    end

    def create
        @feedback = @service.feedbacks.build(feedback_params)
        if @feedback.save
            render "create"
        else
            render "index"
        end
    end

    private

    def set_service
        @service = Service.find(params[:service_id])
    end

    def feedback_params
        params.require(:feedback).permit(
            :body,
            :topic
        )
    end

end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper

    def feedback_topics
        [
           {
                label: "Something is out of date",
                value: "out-of-date"
           },
           {
                label: "I have extra information to add",
                value: "extra-information-to-add"
           },
           {
                label: "The service is closed",
                value: "service-has-closed"
           },
           {
               label: "Something else",
               value: "something-else"
           }
         ]
    end

    def pretty_topic(topic)
        if topic
            topic.gsub('-', ' ').capitalize
        else
            "No topic"
        end
    end

end

app/views/feedback/create.html.erb
<% content_for :title do %>Feedback sent successfully | <% end %>

<% content_for :header do %>
    <div class="confirmation-panel two-thirds">
        <h1 class="confirmation-panel__heading">Your feedback has been sent successfully</h1>
        <p class="confirmation-panel__caption">You can now close this tab</p>
    </div>
<% end %>

app/views/feedback/index.html.erb
<% content_for :title do %>Suggest an edit | <% end %>

<% content_for :header do %>
    <h1 class="page-header__title two-thirds">Suggest an edit</h1>
<% end %>

<%= form_with model: [@service, @feedback], url: service_feedback_index_path(@service), local: true, html: {class: "two-thirds"} do |f| %>

    <%= render "shared/errors", model: @feedback %>

    <fieldset class="field-group field">
        <legend class="field-group__legend">What kind of suggestion?</legend>
        <% feedback_topics.each do |t| %>
            <div class="radio">
                <%= f.radio_button :topic, t[:value], required: true, class: "radio__input" %>
                <%= f.label "topic_#{t[:value]}", t[:label], class: "radio__label" %>
            </div>
        <% end %>
    </fieldset>

    <div class="field">
        <%= f.label :body, "How could this listing be improved?", class: "field__label"%>
        <%= f.text_area :body, required: true, class: "field__input", rows: "3" %>
    </div>

    <div class="form-actions">
        <%= f.submit "Send", class: "button"%>
    </div>

<% end %>